global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alertmanager@example.com'
  smtp_auth_username: 'alertmanager@example.com'
  smtp_auth_password: 'password'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'webhook-demo'

receivers:
  - name: 'webhook-demo'
    webhook_configs:
      - url: 'http://demo-app:8000/webhook/alerts'
        send_resolved: true
        http_config:
          tls_config:
            insecure_skip_verify: true

  - name: 'email-alerts'
    email_configs:
      - to: 'admin@example.com'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
